# justfile — generated by justx · the justfile companion
# https://github.com/amberpixels/just-x
#
# Blocks between `# >>> justx:<id>` and `# <<< justx:<id>` are managed by justx.
# Edit anything outside the fences freely; `j @upgrade` (v2) re-syncs managed blocks.

# standardgo lints itself from source. Every other repo runs
# `go run github.com/amberpixels/standardgo/cmd/standardgo@<ver>`; here that would
# check the published binary instead of the working tree, which is the wrong thing.
# There is no `floor` recipe: standardgo is a binary, so nothing inherits its go
# directive and it tracks the latest Go rather than latest-1.
self := "./cmd/standardgo"

# Default recipe: format (rewrites, decides nothing; `just fix` is the mutable one)
default: fmt

# format Go code - rewrites to canonical form
fmt:
    go run {{ self }} fmt ./...

# lint Go code - reports findings, changes nothing
lint:
    go run {{ self }} ./...

# auto-fix what can be fixed - run on a clean tree and read the diff
fix:
    go run {{ self }} ./... --fix

# >>> justx:test (managed) — `j @upgrade` re-syncs; remove these fences to take over
# run tests
test:
    go test ./...
# <<< justx:test

# >>> justx:build (managed) — `j @upgrade` re-syncs; remove these fences to take over
# build
build:
    go build ./...
# <<< justx:build

# checks that the bundled engine still agrees with the ruleset, mirroring the
# `ruleset` CI job so a Dependabot engine bump can be reviewed locally
verify:
    go run {{ self }} config verify

# run all checks - read-only, safe for CI
ci: build lint test verify
